openapi: "3.0.0"
info:
  version: 1.0.0
  title: Lidraughts.org API reference
  x-logo:
    url: https://lidraughts.org/assets/piece/king-logo.svg
    backgroundColor: #ffffff
  description: "\n\n# Introduction\nWelcome to the reference for the Lidraughts API! Lidraughts is free/libre, open-source draughts server powered by volunteers and donations.\n\n\
  \ - Get help in the [lidraughts developers discord channel](https://discord.gg/9CPhTJQEra).\n\
  \ - [Contribute to this documentation on Github](https://github.com/roepstoep/lidraughts-api).\n\
  \ - Check out [lidraughts widgets to embed in your website](https://lidraughts.org/developers).\n\
  \n## Endpoint\n\
  \ All requests go to `https://lidraughts.org`.\n\
  \n## Rate limiting\n\
  \ All requests are rate limited using various strategies,\
  \ to ensure the API remains responsive for everyone.\n\
  \ Only make one request at a time.\n\
  \ If you receive an HTTP response with a [429 status](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#429),\
  \ please wait a full minute before resuming API usage."
servers:
  - url: https://lidraughts.org
tags:
- name: Account
  description: |
    Read and write account informations and preferences.
    https://lidraughts.org/account/preferences/game-display
- name: Users
  description: |
    Access registered users on Lidraughts.
    https://lidraughts.org/player
- name: Relations
  description: |
    Access relations between users.
- name: Games
  description: |
    Access games played on Lidraughts.
    https://lidraughts.org/games
- name: Teams
  description: |
    Access and manage Lidraughts teams and their members.
    https://lidraughts.org/team
- name: Challenges
  description: |
    Send and receive challenges to play.
- name: External tournaments
  description: |
    Create tournaments on Lidraughts that are externally managed. Lidraughts generates a tournament lobby with upcoming / ongoing games, results and standings. You have full control over the participants and pairings through the API.

    An optional feature is to display FMJD data of the players (photo, real name, rating, title, etc) in the tournament lobby. This data is taken from the most recently published rating list as on [fmjd.org/?p=rating](https://www.fmjd.org/?p=rating).
    Only use this feature when it makes sense in the context of your tournament, and when you are sure the Lidraughts account matches the FMJD ID!
- name: Arena tournaments
  description: |
    Access Arena tournaments played on Lidraughts.
    [Official Arena tournaments](https://lidraughts.org/tournament) are maintained by Lidraughts,
    but you can [create your own Arena tournaments](https://lidraughts.org/tournament/new) as well.
- name: Simuls
  description: |
    Access simuls played on Lidraughts.
    https://lidraughts.org/simul
- name: Studies
  description: |
    Access Lidraughts studies.
    https://lidraughts.org/study
- name: OAuth
  description: |
    Requests taking advantage of OAuth authentication.
    https://lidraughts.org/account/oauth/app
paths:
  /api/users/status:
    get:
      operationId: apiUsersStatus
      summary: Get real-time users status
      description: |
        Read the `online`, `playing` and `streaming` flags of several users.

        This API is very fast and cheap on lidraughts side.
        So you can call it quite often (like once every 5 seconds).

        Use it to track players and know when they're connected on lidraughts and playing games.
      tags:
        - Users
      security:
        - None: []
  /player:
    get:
      operationId: player
      summary: Get all top 10
      tags:
        - Users
      security:
        - SameOrigin: []
      description: |
        Get the top 10 players for each speed and variant.

        See https://lidraughts.org/player.
  /player/top/{nb}/{perfType}:
    get:
      operationId: playerTopNbPerfType
      summary: Get one leaderboard
      tags:
        - Users
      security:
        - SameOrigin: []
      description: |
        Get the leaderboard for a single speed or variant (a.k.a. `perfType`).
        There is no leaderboard for correspondence or puzzles.

        See https://lidraughts.org/player/top/200/bullet.
  /api/user/{username}:
    get:
      operationId: apiUser
      summary: Get user public data
      description: |
        Read public data of a user.
      tags:
        - Users
      security:
        - None: []
  /api/user/{username}/rating-history:
    get:
      operationId: apiUserRatingHistory
      summary: Get rating history of a user
      description: |
        Read rating history of a user, for all perf types.
        There is at most one entry per day.
        Format of an entry is `[year, month, day, rating]`.
        `month` starts at zero (January).
      tags:
        - Users
      security:
        - None: []
  /api/user/{username}/activity:
    get:
      operationId: apiUserActivity
      summary: Get user activity
      description: |
        Read data to generate the activity feed of a user.
      tags:
        - Users
      security:
        - None: []
  /api/users:
    post:
      operationId: apiUsers
      summary: Get users by ID
      tags:
        - Users
      security:
        - None: []
      description: |
        Get up to 300 users by their IDs. Users are returned in the order same order as the IDs.

        The method is `POST` so a longer list of IDs can be sent in the request body.
  /api/account:
    get:
      operationId: accountMe
      summary: Get my profile
      description: |
        Public informations about the logged in user.
      tags:
        - Account
        - OAuth
      security:
        - OAuth2: []
  /api/account/email:
    get:
      operationId: accountEmail
      summary: Get my email address
      description: |
        Read the email address of the logged in user.
      tags:
        - Account
        - OAuth
      security:
        - OAuth2: ["email:read"]
  /api/account/preferences:
    get:
      operationId: account
      summary: Get my preferences
      description: |
        Read the preferences of the logged in user.

        - https://lidraughts.org/account/preferences/game-display
        - https://github.com/roepstoep/lidraughts/blob/master/modules/pref/src/main/Pref.scala
      tags:
        - Account
        - OAuth
      security:
        - OAuth2: ["preference:read"]
  /api/account/kid:
    get:
      operationId: accountKid
      summary: Get my kid mode status
      description: |
        Read the kid mode status of the logged in user.

        - https://lidraughts.org/account/kid
      tags:
        - Account
        - OAuth
      security:
        - OAuth2: ["preference:read"]
    post:
      operationId: accountKidPost
      summary: Set my kid mode status
      description: |
        Set the kid mode status of the logged in user.

        - https://lidraughts.org/account/kid
      tags:
        - Account
        - OAuth
      security:
        - OAuth2: ["preference:write"]
  /game/export/{gameId}:
    get:
      operationId: gamePdn
      summary: Export one game
      description: |
        Download one game in either PDN or JSON format.

        Ongoing games have their last 3 moves omitted, after move 5.
      tags:
        - Games
      security:
        - None: []
  /api/games/user/{username}:
    get:
      operationId: apiGamesUser
      summary: Export games of a user
      description: |
        Download all games of any user in PDN or [ndjson](http://ndjson.org/) format.

        Games are sorted by reverse chronological order (most recent first)

        We recommend streaming the response, for it can be very long (thousands of games).

        The game stream is throttled, depending on who is making the request:
          - Anonymous request: 10 games per second
          - [OAuth2 authenticated](#section/Authentication) request: 20 games per second
          - Authenticated, downloading your own games: 50 games per second
      tags:
        - Games
        - OAuth
      security:
        - None: []
        - OAuth2: []
  /games/export/_ids:
    post:
      operationId: gamesExportIds
      summary: Export games by IDs
      description: |
        Download games by IDs in PDN or [ndjson](http://ndjson.org/) format.

        Games are sorted by reverse chronological order (most recent first)

        The method is `POST` so a longer list of IDs can be sent in the request body.

        300 IDs can be submitted.

        Ongoing games have their last 3 moves omitted, after move 5.
      tags:
        - Games
      security:
        - SameOrigin: []
  /api/stream/games-by-users:
    post:
      operationId: gamesByUsers
      summary: Stream current games
      description: |
        Stream the games played between a list of users, in real time.
        Only games where **both players** are part of the list are included.

        Maximum number of users: 300.

        **Games are streamed as [ndjson](http://ndjson.org/)**, i.e. one JSON object per line.

        The method is `POST` so a longer list of IDs can be sent in the request body.
      tags:
        - Games
      security:
        - None: []
  /api/account/playing:
    get:
      operationId: apiAccountPlaying
      summary: Get ongoing games
      description: |
        Get the ongoing games of the current user.
        Real-time and correspondence games are included.
        The most urgent games are listed first.
      tags:
        - Games
        - OAuth
      security:
        - OAuth2: []
  /tv/feed:
    get:
      operationId: tvFeed
      summary: Stream current TV game
      description: |
        Stream positions and moves of the current [TV game](https://lidraughts.org/tv) in [ndjson](http://ndjson.org/).
        A summary of the game is sent as a first message, and when the featured game changes.

        Try it with `curl https://lidraughts.org/tv/feed`.
      tags:
        - Games
      security:
        - SameOrigin: []
  /api/tournament:
    get:
      operationId: apiTournament
      summary: Get current tournaments
      description: |
        Get recently finished, ongoing, and upcoming tournaments.

        This API is used to display the [Lidraughts tournament schedule](https://lidraughts.org/tournament).
      tags:
        - "Arena tournaments"
      security:
        - None: []
    post:
      operationId: apiTournamentPost
      summary: Create a new Arena tournament
      description: |
        Create a public or private Arena tournament.

        This endpoint mirrors the form on https://lidraughts.org/tournament/new.

        You can create up to 12 public tournaments per day, or 24 private tournaments.

        A team battle can be created by specifying the `teambBattleByTeam` argument.
      tags:
        - "Arena tournaments"
      security:
        - OAuth2: ["tournament:write"]
  /api/tournament/{id}:
    get:
      operationId: tournament
      summary: Get info about an Arena tournament
      description: |
        Get detailed info about recently finished, current, or upcoming tournament's duels, player standings, and other info.
      tags:
        - "Arena tournaments"
      security:
        - None: []
  /api/tournament/{id}/games:
    get:
      operationId: gamesByTournament
      summary: Export games of an Arena tournament
      description: |
        Download games of a tournament in PDN or [ndjson](http://ndjson.org/) format.

        Games are sorted by reverse chronological order (most recent first)
      tags:
        - "Arena tournaments"
      security:
        - None: []
  /api/tournament/{id}/results:
    get:
      operationId: resultsByTournament
      summary: Get results of an Arena tournament
      description: |
        Players of an Arena tournament, with their score and performance, sorted by rank (best first).

        **Players are streamed as [ndjson](http://ndjson.org/)**, i.e. one JSON object per line.

        If called on an ongoing tournament, results can be inconsistent
        due to ranking changes while the players are being streamed.
        Use on finished tournaments for guaranteed consistency.
      tags:
        - "Arena tournaments"
      security:
        - None: []
  /api/tournament/{id}/teams:
    get:
      operationId: teamsByTournament
      summary: Get team standing of a team battle
      description: |
        Teams of a team battle tournament, with top players, sorted by rank (best first).
      tags:
        - "Arena tournaments"
      security:
        - None: []
  /api/user/{username}/tournament/created:
    get:
      operationId: apiUserNameTournamentCreated
      summary: Get tournaments created by a user
      description: |
        Get all tournaments created by a given user.

        Tournaments are sorted by reverse chronological order of start date (last starting first).

        **Tournaments are streamed as [ndjson](http://ndjson.org/)**, i.e. one JSON object per line.
      tags:
        - "Arena tournaments"
      security:
        - None: []
  /api/tournament/external:
    post:
      operationId: apiExternalTournamentCreate
      summary: Create a new external tournament
      description: |
        Create a new external tournament.

        By default the players are visible in the tournament lobby with their lidraughts username, rating and title.
        When `userDisplay` is set to `fmjd`, these are replaced with the values from the FMJD database (full name, FMJD rating, FMJD title) where available.
      tags:
        - "External tournaments"
      security:
        - OAuth2: ["tourext:write"]
  /api/tournament/external/{id}:
    get:
      operationId: apiExternalTournament
      summary: Get info about an external tournament
      description: |
        Get detailed tournament info, including players and upcoming games. Only allowed for tournaments created by you.
      tags:
        - "External tournaments"
      security:
        - OAuth2: ["tourext:write"]
    post:
      operationId: apiExternalTournamentUpdate
      summary: Update an external tournament
      description: |
        Update an external tournament.

        Once games have been added to the tournament, the game settings can no longer be changed: `variant`, `clock`, `days`, `rated`, `microMatches`, `autoStartGames`
      tags:
        - "External tournaments"
      security:
        - OAuth2: ["tourext:write"]
  /api/tournament/external/{id}/player:
    post:
      operationId: apiExternalTournamentPlayerCreate
      summary: Add a new player
      description: |
        Invite a user to play in your tournament. Only invite users if you know they want to participate. Users don't receive a notification when invited.

        If an FMJD ID is specified, there will be an extra section in the player details in the tournament lobby, that shows the public [FMJD profile](https://www.fmjd.org/?p=pcard&id=10122) information such as photo, full name, rating, etc.
        When the tournament has `userDisplay` set to `fmjd`, the same information will be visible in the tournament lobby instead of the Lidraughts username, rating and title.

        When an invited player opens the tournament lobby, they will see a prompt that asks if they agree to join. It contains an explanation of the tournament rules, and their FMJD ID if you specified one.
      tags:
        - "External tournaments"
      security:
        - OAuth2: ["tourext:write"]
  /api/tournament/external/{id}/bye:
    post:
      operationId: apiExternalTournamentBye
      summary: Give a player a bye
      description: |
        Give a player a half or full point bye. Only possible if the tournament has rounds.
      tags:
        - "External tournaments"
      security:
        - OAuth2: ["tourext:write"]
  /api/tournament/external/{id}/player/{userId}:
    delete:
      operationId: apiExternalTournamentPlayerDelete
      summary: Delete a player
      description: |
        Delete a player. Only possible if the player has no upcoming / ongoing / finished games.
      tags:
        - "External tournaments"
      security:
        - OAuth2: ["tourext:write"]
  /api/tournament/external/{id}/game:
    post:
      operationId: apiExternalTournamentGameCreate
      summary: Create a new tournament game
      description: |
        Create new game in the tournament that is set to start at a specific date/time. Only possible if both players have agreed to join.

        If the tournament has `autoStartGames` set to `true`, the game will start automatically at the starting date/time. If a player is not present they will lose on time once the clock runs out.
        If `autoStartGames` is set to `false` a Join button will appear at the starting date/time. The clocks will start once both players have joined the game.
      tags:
        - "External tournaments"
      security:
        - OAuth2: ["tourext:write"]
  /api/tournament/external/{id}/game/{gameId}:
    delete:
      operationId: apiExternalTournamentGameDelete
      summary: Delete an upcoming tournament game
      description: |
        Delete an upcoming tournament game. Has no effect once the game has started.
      tags:
        - "External tournaments"
      security:
        - OAuth2: ["tourext:write"]
  /study/{studyId}/{chapterId}.pdn:
    get:
      operationId: studyChapterPdn
      summary: Export one study chapter
      description: |
        Download one study chapter in PDN format.
      tags:
        - Studies
      security:
        - SameOrigin: []
  /study/{studyId}.pdn:
    get:
      operationId: studyChapterPdn
      summary: Export all chapters
      description: |
        Download all chapters of a study in PDN format.
      tags:
        - Studies
      security:
        - SameOrigin: []
  /api/simul:
    get:
      operationId: apiSimul
      summary: Get current simuls
      description: |
        Get recently finished, ongoing, and upcoming simuls.
      tags:
        - Simuls
      security:
        - None: []
  /api/simul/{id}/games:
    get:
      operationId: gamesBySimul
      summary: Export games of a simul
      description: |
        Download games of a simul in PDN or [ndjson](http://ndjson.org/) format.
      tags:
        - Simuls
      security:
        - None: []
  /team/{teamId}/join:
    post:
      operationId: teamIdJoin
      summary: Join a team
      description: |
        Join a team.
        If the team join policy requires a confirmation,
        and the team owner is not the oAuth app owner,
        then the call fails with `403 Forbidden`.
      tags:
        - Teams
        - OAuth
      security:
        - OAuth2: ["team:write"]
          SameOrigin: []
  /team/{teamId}/quit:
    post:
      operationId: teamIdQuit
      summary: Leave a team
      description: |
        Leave a team.
        - https://lidraughts.org/team
      tags:
        - Teams
        - OAuth
      security:
        - OAuth2: ["team:write"]
          SameOrigin: []
  /team/{teamId}/kick/{userId}:
    post:
      operationId: teamIdKickUserId
      summary: Kick a user from your team
      description: |
        Kick a member out of one of your teams.
        - https://lidraughts.org/team
      tags:
        - Teams
        - OAuth
      security:
        - OAuth2: ["team:write"]
          SameOrigin: []
  /team/{teamId}/pm-all:
    post:
      operationId: teamIdPmAll
      summary: Message all members
      description: |
        Send a private message to all members of a team.
        You must own the team.
      tags:
        - Teams
        - OAuth
      security:
        - OAuth2: ["team:write"]
  /streamer/live:
    get:
      operationId: streamerLive
      summary: Get live streamers
      description: |
        Get basic info about currently streaming users.

        This API is very fast and cheap on lidraughts side.
        So you can call it quite often (like once every 5 seconds).
      tags:
        - Users
      security:
        - None: []
          SameOrigin: []
  /api/crosstable/{user1}/{user2}:
    get:
      operationId: apiCrosstable
      summary: Get crosstable
      description: |
        Get total number of games, and current score, of any two users.

        If the `matchup` flag is provided, and the users are currently playing, also gets the current match game number and scores.
      tags:
        - Users
      security:
        - None: []
  /api/user/{username}/following:
    get:
      operationId: apiUserFollowing
      summary: Get users followed by a user
      description: |
        **Users are streamed as [ndjson](http://ndjson.org/)**, i.e. one JSON object per line.
      tags:
        - Relations
      security:
        - None: []
  /api/user/{username}/followers:
    get:
      operationId: apiUserFollowers
      summary: Get users who follow a user
      description: |
        **Users are streamed as [ndjson](http://ndjson.org/)**, i.e. one JSON object per line.
      tags:
        - Relations
      security:
        - None: []
  /api/stream/event:
    get:
      operationId: apiStreamEvent
      summary: Stream incoming events
      description: "\n
      \ Stream the events reaching a lidraughts user in real time as [ndjson](http://ndjson.org/).\n\n
      \ Each line is a JSON object containing a `type` field. Possible values are:\n
      \ - `gameStart` Start of a game\n
      \ - `challenge` A player sends you a challenge\n
      \n
      \ When the stream opens, all current challenges and games are sent."
      tags:
        - Bot
        - Challenges
      security:
        - OAuth2: ["challenge:read", "bot:play"]
  /api/bot/account/upgrade:
    post:
      operationId: botAccountUpgrade
      summary: Upgrade to Bot account
      description: |
        Upgrade a lidraughts player account into a Bot account. Only Bot accounts can use the Bot API.

        The account **cannot have played any game** before becoming a Bot account. The upgrade is **irreversible**. The account will only be able to play as a Bot.

        To know if an account has already been upgraded, use the [Get my profile API](#operation/accountMe):
        the `title` field should be set to `BOT`.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/stream/{gameId}:
    get:
      operationId: botGameStream
      summary: Stream Bot game state
      description: "\
      \ Stream the state of a game being played with the Bot API, as [ndjson](http://ndjson.org/).\n\
      \nUse this endpoint to get updates about the game in real-time, with a single request.\n\
      \nEach line is a JSON object containing a `type` field. Possible values are:\n
      \ - `gameFull` Full game data. All values are immutable, except for the `state` field.\n
      \ - `gameState` Current state of the game. Immutable values not included.\n
      \ - `chatLine` Chat message sent by a user (or the bot itself) in the `room` \"player\" or \"spectator\".\n\n
      \nThe first line is always of type `gameFull`."
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/{gameId}/move/{move}:
    post:
      operationId: botGameMove
      summary: Make a Bot move
      description: |
        Make a move in a game being played with the Bot API.

        The move can also contain a draw offer/agreement.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/{gameId}/chat:
    post:
      operationId: botGameChat
      summary: Write in the chat
      description: |
        Post a message to the player or spectator chat, in a game being played with the Bot API.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/{gameId}/abort:
    post:
      operationId: botGameAbort
      summary: Abort a game
      description: |
        Abort a game being played with the Bot API.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/bot/game/{gameId}/resign:
    post:
      operationId: botGameResign
      summary: Resign a game
      description: |
        Resign a game being played with the Bot API.
      tags:
        - Bot
      security:
        - OAuth2: ["bot:play"]
  /api/challenge/{username}:
    post:
      operationId: challengeCreate
      summary: Create a challenge
      description: |
        Challenge someone to play. The targeted player can choose to accept or decline.

        If the challenge is accepted, you will be notified on the [event stream](#operation/apiStreamEvent)
        that a new game has started. The game ID will be the same as the challenge ID.

        If you also have an OAuth token with `challenge:write` scope for the receiving user,
        you can make them accept the challenge immediately by setting the `acceptByToken` field.
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write", "bot:play"]
  /api/challenge/{challengeId}/accept:
    post:
      operationId: challengeAccept
      summary: Accept a challenge
      description: |
        Accept an incoming challenge.

        You should receive a `gameStart` event on the [incoming events stream](#operation/apiStreamEvent).
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write", "bot:play"]
  /api/challenge/{challengeId}/decline:
    post:
      operationId: challengeDecline
      summary: Decline a challenge
      description: |
        Decline an incoming challenge.
      tags:
        - Challenges
      security:
        - OAuth2: ["challenge:write", "bot:play"]
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: "### Authorization Code Flow\n\
        \ The authorization code flow allows your users to **login with lidraughts**.\n\
        \ - [NodeJS example](https://github.com/roepstoep/lidraughts-api/tree/master/example/oauth-authorization-code)\n\
        \ - [Create a Lidraughts OAuth app](https://lidraughts.org/account/oauth/app)\n\
        \ - [About authorization code flow](https://www.digitalocean.com/community/tutorials/an-introduction-to-oauth-2#grant-type-authorization-code)\n\
        \n### Personal API Token\n\
        \ Personal API tokens allow you to quickly interact with Lidraughts OAuth API.\n\
        \ - `curl https://lidraughts.org/api/account -H \"Authorization: Bearer <token>\"`\n\
        \ - [NodeJS example](https://github.com/roepstoep/lidraughts-api/tree/master/example/oauth-personal-token)\n\
        \ - [Generate a personal API token](https://lidraughts.org/account/oauth/token)"
      flows:
        authorizationCode:
          authorizationUrl: https://oauth.lidraughts.org/oauth/authorize
          tokenUrl: https://oauth.lidraughts.org/oauth
          scopes:
            "preference:read": Read your preferences
            "preference:write": Write your preferences
            "email:read": Read your email address
            "challenge:read": Read incoming challenges
            "challenge:write": Create, accept, decline challenges
            "tournament:write": Create tournaments
            "tourext:write": Manage external tournaments
            "puzzle:read": Read puzzle activity
            "team:write": Join, leave, and manage teams
            "bot:play": Play with the Bot API. Only for [Bot accounts](#operation/botAccountUpgrade)
    SameOrigin:
      description: "CORS is supported on almost all endpoints, except those tagged `SameOrigin`."
      type: none
    None:
      description: "No authorization required.\n\
        \ For requests that don't need an authenticated user."
      type: none
